// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NutritionRecettes.Data;

#nullable disable

namespace NutritionRecettes.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260520171943_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("NutritionRecettes.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CaloriesParUnite")
                        .HasColumnType("REAL");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unite")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CaloriesParUnite = 3.6400000000000001,
                            Nom = "Farine de blé",
                            Unite = "g"
                        },
                        new
                        {
                            Id = 2,
                            CaloriesParUnite = 3.8700000000000001,
                            Nom = "Sucre",
                            Unite = "g"
                        },
                        new
                        {
                            Id = 3,
                            CaloriesParUnite = 8.8399999999999999,
                            Nom = "Huile d'olive",
                            Unite = "ml"
                        },
                        new
                        {
                            Id = 4,
                            CaloriesParUnite = 78.0,
                            Nom = "Œuf",
                            Unite = "pièce"
                        },
                        new
                        {
                            Id = 5,
                            CaloriesParUnite = 22.0,
                            Nom = "Tomate",
                            Unite = "pièce"
                        },
                        new
                        {
                            Id = 6,
                            CaloriesParUnite = 44.0,
                            Nom = "Oignon",
                            Unite = "pièce"
                        },
                        new
                        {
                            Id = 7,
                            CaloriesParUnite = 1.6499999999999999,
                            Nom = "Poulet (filet)",
                            Unite = "g"
                        },
                        new
                        {
                            Id = 8,
                            CaloriesParUnite = 3.5,
                            Nom = "Riz",
                            Unite = "g"
                        },
                        new
                        {
                            Id = 9,
                            CaloriesParUnite = 3.71,
                            Nom = "Pâtes",
                            Unite = "g"
                        },
                        new
                        {
                            Id = 10,
                            CaloriesParUnite = 0.60999999999999999,
                            Nom = "Lait",
                            Unite = "ml"
                        },
                        new
                        {
                            Id = 11,
                            CaloriesParUnite = 7.1699999999999999,
                            Nom = "Beurre",
                            Unite = "g"
                        },
                        new
                        {
                            Id = 12,
                            CaloriesParUnite = 0.77000000000000002,
                            Nom = "Pomme de terre",
                            Unite = "g"
                        });
                });

            modelBuilder.Entity("NutritionRecettes.Models.Recette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("NbPersonnes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TypeCuisine")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Recettes");
                });

            modelBuilder.Entity("NutritionRecettes.Models.RecetteIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantite")
                        .HasColumnType("REAL");

                    b.Property<int>("RecetteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecetteId");

                    b.ToTable("RecetteIngredients");
                });

            modelBuilder.Entity("NutritionRecettes.Models.RecetteIngredient", b =>
                {
                    b.HasOne("NutritionRecettes.Models.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutritionRecettes.Models.Recette", null)
                        .WithMany("Ingredients")
                        .HasForeignKey("RecetteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("NutritionRecettes.Models.Recette", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
